# -*- coding: utf-8 -*-
"""llm-project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L_KlcxM_bTF-EFtE1joR4GS66JALu0wd
"""

!python --version

import torch
print("CUDA متاح؟", torch.cuda.is_available())

!pip -q install transforms accelerate sentencepiece

from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")

out = generator(
    "Once upon a time in the world of AI,",
    max_new_tokens=10,
    do_sample=True,
    temperature=0.8,
    top_p=0.9
)

print(out[0]['generated_text'])

from transformers import pipeline

aragpt = pipeline("text-generation", model="aubmindlab/aragpt2-medium")

prompt = "اكتب فقرة قصيرة عن مستقبل الذكاء الاصطناعي:"

out = aragpt(
    prompt,
    max_new_tokens=80,         # زيادة الطول شوية عشان يعطي معنى كامل
    do_sample=True,            # أخذ عينات عشوائية
    temperature=0.8,           # تنويع بدون إفراط
    top_p=0.9,                 # nucleus sampling (أفضل من 1.0)
    repetition_penalty=1.3,    # نرفع العقوبة لتقليل التكرار أكثر
    no_repeat_ngram_size=3     # يمنع تكرار نفس 3 كلمات متتالية
)

print(out[0]['generated_text'])

from transformers import pipeline
qa= pipeline("question-answering",model= "deepset/roberta-base-squad2")
context="python is apopular programming language created by Guido van Rossum and released in 1991.It is widly used in data science , AI, web development, and automation."
result=qa(question="who created python?", context=context)
print(result)

from transformers import pipeline
t2t= pipeline("text2text-generation",model="google/flan-t5-small")
print(t2t("Translate to Arabic: Machine Learning is fun.")[0]["generated_text"])
print(t2t("Summarize: Large Language Models are tranforming how we build apps.")[0]["generated_text"])
print(t2t("Write a polite email to request a meeting tommorow")[0]["generated_text"])

from transformers import pipeline

summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

text = (
    "Artificial intelligence is rapidly evolving and being integrated into various industries. "
    "Companies are exploring applications in healthcare, finance, and education to improve efficiency "
    "and decision-making. However, ethical considerations and responsible deployment remain critical."
)
print(summarizer(text, max_length=60, min_length=25, do_sample=False)[0]["summary_text"])

from transformers import pipeline
import pandas as pd
summarize = pipeline("summarization" , model="facebook/bart-large-cnn")
qa=pipeline("question-answering" , model="deepset/roberta-base-squad2")
context="Artificial intelligence is rapidly evoling and being integrated into varioous industries.Companies are exploring applications in healthcare , finance , and education to improve efficiency and decision-making . However ,ethical consideration and responsible deployment remain critical."
summary= summarize(context, max_length=60, min_length=25, do_sample=False)[0]["summary_text"]
question= "which industries are useing AI?"
answer= qa(question=question , context=context)["answer"]

data={
    "orginal Text" :[context],
    "Summary":[summary],
    "Question":[question],
    "Answer":[answer]
}
df=pd.DataFrame(data)
print(df)

from transformers import pipeline
import pandas as pd
summarizer = pipeline("summarization" , model="facebook/bart-large-cnn")
qa=pipeline("question-answering" , model="deepset/roberta-base-squad2")
aragpt=pipeline("text-generation", model="aubmindlab/aragpt2-medium")
texts=["Artificial intelligence is rapidly evoling and being integrated into varioous industries.Companies are exploring applications in healthcare , finance , and education to improve efficiency and decision-making . However ,ethical consideration and responsible deployment remain critical.",
"python is one of most popular programming languages in the world. It us widely used in data science, machine learning,web development ,and automation. Its simplicity and readability make it beginner-friendly."
]
questions_list=[
    ["Which industres are using AI?" , "What is important for responsible deployment?"],
    ["What is python used for?" , "Whay is python  beginner-friendly"]
]
all_data=[]
for text, questions in zip(texts, questions_list):
    summary = summarizer(text, max_length=40, min_length=15, do_sample=False)[0]["summary_text"]

    for question in questions:
        answer = qa(question=question, context=text)["answer"]

        all_data.append({
            "Original Text": text,
            "Summary": summary,
            "Question": question,
            "Answer": answer
        })
df=pd.DataFrame(all_data)
df.to_csv("LLM_Project_Result.csv",index=False)
df.to_excel("LLM_Project_Result.xlsx",index=False)
print("تم انشاء النتائج وتصديرها بنجاح ")
print(df)

# 1) استيراد المكتبات
!pip install transformers torch pandas openpyxl --quiet

from transformers import pipeline
import pandas as pd
from google.colab import files

# 2) إعداد الـ Pipelines
generator = pipeline("text-generation", model="aubmindlab/aragpt2-medium")   # نموذج عربي
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")     # للتلخيص
translator = pipeline("translation", model="Helsinki-NLP/opus-mt-en-ar")    # للترجمة

# 3) تنفيذ المهام
prompt = "اكتب فقرة قصيرة عن المستقبل التقني والذكاء الاصطناعي:"
gen_text = generator(prompt, max_new_tokens=80, do_sample=True, temperature=0.8, top_p=0.95)[0]["generated_text"]

summary = summarizer(gen_text, max_length=60, min_length=20, do_sample=False)[0]["summary_text"]

translation = translator("Artificial Intelligence is shaping the future of humanity.", max_length=50)[0]["translation_text"]

# 4) حفظ النتائج في DataFrame
df = pd.DataFrame({
    "Task": ["Generation (Ar)", "Summarization", "Translation (En→Ar)"],
    "Result": [gen_text, summary, translation]
})

# 5) حفظ كملف Excel
df.to_excel("LLM_Project_Results.xlsx", index=False)

# 6) تنزيل الملف على جهازك
files.download("LLM_Project_Results.xlsx")

!pip install transformers
from transformers import pipeline
analyzer = pipeline("sentiment-analysis")
texts= ["I love working with AI!", "I am very tired tody.", "The movie was not okay."]
for t in texts:
  result = analyzer(t)[0]
  print(f"النص:{t}")
  print(f"التصنيف: {result["label"]} | النتيجة: {result["score"]:2f}\n")

!pip install keybert
from keybert import KeyBERT
kw_model = KeyBERT()
doc = "Saudi Arabia is investing heavily in Artificial Intelligence and digital transformation project."
keyword= kw_model.extract_keywords(doc, top_n=5)

print ("النص:", doc)
print ("الكلمات المفتاحية:" , keyword)

!pip install pandas transformers openpyxl
import pandas as pd
from transformers import pipeline

from google.colab import files
upload=files.upload()


df= pd.read_csv(list(upload.keys())[0])


print("أول 5 أسطر من البيانات ")
print(df.head())

sentiment_model= pipeline("sentiment-analysis" , model="nlptown/bert-base-multilingual-uncased-sentiment")


df["Sentiment"] = df["comment"].apply(lambda x: sentiment_model(str(x))[0]["label"])


print("/n البيانات بعد التحليل:")
print(df.head())

output_path = "comments_with_sentiment.xlsx"
df.to_excel(output_path, index=False)

print("تم انشاء الملف بنجاح :{output_path}")
files.download(output_path)